# Generated by Django 3.2.20 on 2023-09-06 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_wishlist_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
