# Generated by Django 3.2.20 on 2023-09-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_remove_wishlist_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
    ]
